### PR TITLE
Cross build against sbt 0.13 & 1.0

### PR DESCRIPTION
**Pull request by metasim**

### CODE REVIEW

**Comment by metasim** [comment]
@naderghanbari Can you elucidate on whether there's intent to maintain this plugin, or if it's abandonware in need of a maintained fork?

**Comment by naderghanbari** [comment]
I'm really sorry for the late reply. There is definitely an intent to maintain this. 

For the current PR, (just to confirm) it's gonna work with both SBT 0.13 and 1.x after this PR is merged, right?

**Review by naderghanbari — APPROVED** [review]

**Comment by metasim** [comment]
@naderghanbari Yes, I've personally used it with both 0.13 and 1.0 projects.

**Comment by metasim** [comment]
Closed due to lack of maintainer interest.

**Pull request closed without merging**
