### PR TITLE
linux compatibility and more

### PR DESCRIPTION
**Pull request by andreaTP**
A number of tiny fixes to enhance output and a fix to check git on linux

### CODE REVIEW

**Comment by mgodlewski** [comment]
Nice, this should fix isses #5 and #7 !

**Comment by ches** [comment]
@naderghanbari Are you able to give feedback on this?

I'm evaluating using the plugin at work but if it's not being actively maintained then I'll have to be willing to commit to maintaining an internal fork, and publish our own private artifacts. I'd rather know that I can contribute back to the upstream and have proposals actively reviewed and integrated.

On that note, does your license note section in the README mean that you license your work on this fork under Apache 2 like the original? If so, it'd be great if you could explicitly state in writing that this fork remains licensed as Apache 2, it's currently ambiguous.

**Comment by naderghanbari** [comment]
@ches Sorry for the late reply. I will try to maintain this repo. 

It will be Apache 2 like the original, I will add a license file.

**Comment by naderghanbari** [comment]
@andreaTP Thanks for contribution and sorry for the late reply. I assume it's not fair to ask for improvements this late otherwise I would have asked you to submit separate PRs for each concern. The commits are clear and atomic though so I'm gonna merge it.

**Pull request merged**
